version: '3.8'

services:
  web:
    build: .
    command: bash -c "poetry run python event_management/manage.py migrate && poetry run python event_management/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=event_management.settings
